# Generated by Django 3.1.5 on 2022-09-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='score',
            field=models.IntegerField(),
        ),
    ]
