# Generated by Django 3.1.5 on 2022-09-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_auto_20220929_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
